# global:
#   external_labels:
#     foo: bar
#
# prometheus:
#   output: gossiping.yml
#
# tasks:
#   dry_run: true
#   states: ./
#

global:
  external_labels:
    az: cn-hangzhou-g

tasks:
  states: ./